schema_version = "1.0.0"
id = "MBCollector672_import_mis"
version = "1.2.0"
name = "Import Mis"
tagline = "mis/mcs (Marble Blast mission file) importer for Blender"
maintainer = "MBCollector672"
type = "add-on"
website = "https://github.com/MBCollector672/import_mis"
blender_version_min = "4.2.0"
blender_version_max = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
[permissions]
files = "Read/write configs"
